spring:
  server:
    port: 8080

  application:
    name: bookcover

  datasource:
    url: jdbc:postgresql://localhost:5432/bookcover
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/bookcover

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: bookcover
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true