spring:
  application:
    name: bookcover


#  autoconfigure:
#      exclude:
#          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#          - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#          - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
#          - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update